#!/bin/sh

current_dir=$(cd "$(dirname "$0")" && pwd)
OUT_FILE="$current_dir/post.txt"
commit_date=$(date '+%Y/%m/%d %H:%M:%S')
commit_SHA_long=$(git rev-parse HEAD)
commit_SHA_short=$(git rev-parse --short HEAD)
commit_message=$(git log --oneline | grep "$commit_SHA_short" | awk '{print $2}')

first_add_file=true
first_modified_file=true

{
  echo "## Commit: [$commit_SHA_short](https://github.com/virtualitypage/AdGuardHome_Filters/commit/$commit_SHA_long) - $commit_message"
  echo
  echo "### Date"
  echo
  echo "- $commit_date"
  echo
} >> "$OUT_FILE"

# git show --name-status "$commit_SHA_short" | grep '^[MA]' | sed 's/Author.*//g' > /Volumes/dev/GitHub/AdGuardHome_Filters/a
git diff --name-status HEAD^ > /Volumes/dev/GitHub/AdGuardHome_Filters/a
while IFS= read -r line; do
  if echo "$line" | grep -q '^A'; then
    if $first_add_file; then
      {
        echo
        echo "### Add"
        echo
      } >> "$OUT_FILE"
      first_add_file=false
    fi
    added=$(echo "$line" | awk '{print $2}')
    echo "- $added" >> "$OUT_FILE"
  elif echo "$line" | grep -q '^M'; then
    if $first_modified_file; then
      {
        echo "### Change"
        echo
      } >> "$OUT_FILE"
      first_modified_file=false
    fi
    modified=$(echo "$line" | awk '{print $2}')
    git diff HEAD^ "$modified" > /Volumes/dev/GitHub/AdGuardHome_Filters/b
    # sed -i '' -e 's/+++ b\///g' -e 's/@@ .*//g' -e 's/^ /    /g' -e 's/^+/    +/g' -e 's/^-/    -/g' -e 's/    $//g' -e '1,5d' /Volumes/dev/GitHub/AdGuardHome_Filters/b
    sed -i '' -e 's/+++ b\///g' -e 's/^ /    /g' -e 's/^+/    +/g' -e 's/^-/    -/g' -e 's/    $//g' -e '1,5d' /Volumes/dev/GitHub/AdGuardHome_Filters/b
    echo "- $modified" >> "$OUT_FILE"
    cat << EOF >> "$OUT_FILE"
    \`\`\`yaml
$(cat /Volumes/dev/GitHub/AdGuardHome_Filters/b)
    \`\`\`

EOF
  fi
done < "/Volumes/dev/GitHub/AdGuardHome_Filters/a"
