#!/bin/sh

repo="/Volumes/dev/GitHub/AdguardFilter_prototype"
commit_date=$(date '+%Y/%m/%d %H:%M:%S')
commit_SHA_long=$(git rev-parse HEAD)
commit_SHA_short=$(git rev-parse --short HEAD)
commit_message=$(git log --oneline | grep "$commit_SHA_short" | awk '{print $2}')

first_add_file=true
first_modified_file=true

{
  echo "## Commit: [$commit_SHA_short](https://github.com/virtualitypage/AdguardFilter_prototype/commit/$commit_SHA_long) - $commit_message"
  echo
  echo "### Date"
  echo
  echo "- $commit_date"
  echo
} >> "$repo/post"

# git show --name-status "$commit_SHA_short" | grep '^[MA]' | sed 's/Author.*//g' > "$repo/status"
git diff --name-status HEAD^ > "$repo/status"
while IFS= read -r line; do
  if echo "$line" | grep -q '^A'; then
    if $first_add_file; then
      {
        echo
        echo "### Add"
        echo
      } >> "$repo/post"
      first_add_file=false
    fi
    added=$(echo "$line" | awk '{print $2}')
    echo "- $added" >> "$repo/post"
  elif echo "$line" | grep -q '^M'; then
    if $first_modified_file; then
      {
        echo "### Change"
        echo
      } >> "$repo/post"
      first_modified_file=false
    fi
    modified=$(echo "$line" | awk '{print $2}')
    git diff HEAD^ "$modified" > "$repo/diff"
    # sed -i '' -e 's/+++ b\///g' -e 's/@@ .*//g' -e 's/^ /    /g' -e 's/^+/    +/g' -e 's/^-/    -/g' -e 's/    $//g' -e '1,5d' "$repo/diff"
    sed -i '' -e 's/+++ b\///g' \
              -e 's/^ /    /g' \
              -e 's/^+/    +/g' \
              -e 's/^-/    -/g' \
              -e 's/    $//g' \
              -e '/\\ No newline at end of file/d' \
              -e '1,5d' "$repo/diff"
    echo "- $modified" >> "$repo/post"
    cat << EOF >> "$repo/post"
    \`\`\`yaml
$(cat "$repo/diff")
    \`\`\`

EOF
  fi
done < "$repo/status"

sed -i '' '4r '"$repo/post" "$repo/CommitLog.md"
rm "$repo/diff" "$repo/status" "$repo/post"
